import { hashId,cleanText,safeDate,normalizeFormat,classifyElectronic } from "./normalize.mjs";
const TERMS=["techno","hard techno","schranz","rave","house music","trance","drum and bass","hardstyle","hardcore rave","psytrance","acid techno","warehouse rave"];
async function jsonFetch(url,timeout=7000){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(url,{signal:c.signal,headers:{"user-agent":"EventTrack/0.3","accept":"application/json"}});if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json()}finally{clearTimeout(t)}}
function fromStung(e,term){
  const title=cleanText(e.title||e.name,220),startDate=safeDate(e.start_utc||e.start_date||e.start);if(!title||!startDate)return null;
  const ctx=`${title} ${e.category||""} ${e.genre||""} ${e.genres||""} ${e.description||""}`,cls=classifyElectronic(ctx,{tags:term});if(!cls.relevant)return null;
  const city=cleanText(e.city,100),country=cleanText(e.country||e.country_name||e.country_code,100),format=normalizeFormat(ctx),url=cleanText(e.ticket_url||e.url||e.event_url||"",500);
  return{id:hashId(title.toLowerCase(),startDate.slice(0,10),city.toLowerCase(),country.toLowerCase()),title,startDate,endDate:safeDate(e.end_utc||e.end_date),venue:cleanText(e.venue_name||e.venue,150),city,region:cleanText(e.region||e.state,100),country,category:format,format,genres:cls.genres,description:cleanText(e.description||"",700),imageUrl:cleanText(e.image_url||e.image||"",500),eventUrl:url,sourceId:"builtin-stungevents",sourceName:"StungEvents",sourceUrl:"https://stungevents.com",confidence:80,verified:false,verificationLevel:"global-aggregator",evidenceUrls:[url].filter(Boolean),manual:false,discoveredAt:new Date().toISOString(),updatedAt:new Date().toISOString()};
}
async function collectStung(){const out=[];for(const term of TERMS){try{const data=await jsonFetch(`https://api.stungevents.com/search?q=${encodeURIComponent(term)}`);for(const e of data.events||[]){const n=fromStung(e,term);if(n)out.push(n)}}catch{}}return out}
function fromTM(e,term){
  const title=cleanText(e.name,220),startDate=safeDate(e.dates?.start?.dateTime||e.dates?.start?.localDate);if(!title||!startDate)return null;
  const v=e._embedded?.venues?.[0]||{},c=e.classifications?.[0]||{},ctx=`${title} ${c.genre?.name||""} ${c.subGenre?.name||""}`,cls=classifyElectronic(ctx,{tags:term});if(!cls.relevant)return null;
  const city=cleanText(v.city?.name,100),country=cleanText(v.country?.name||v.country?.countryCode,100),format=normalizeFormat(ctx),image=[...(e.images||[])].sort((a,b)=>(b.width||0)-(a.width||0))[0]?.url||"";
  return{id:hashId(title.toLowerCase(),startDate.slice(0,10),city.toLowerCase(),country.toLowerCase()),title,startDate,endDate:null,venue:cleanText(v.name,150),city,region:cleanText(v.state?.name,100),country,category:format,format,genres:cls.genres,description:cleanText(e.info||e.pleaseNote||"",700),imageUrl:image,eventUrl:e.url||"",sourceId:"builtin-ticketmaster",sourceName:"Ticketmaster",sourceUrl:"https://ticketmaster.com",confidence:96,verified:true,verificationLevel:"primary-ticketing",evidenceUrls:[e.url].filter(Boolean),manual:false,discoveredAt:new Date().toISOString(),updatedAt:new Date().toISOString()};
}
async function collectTM(){const key=process.env.TICKETMASTER_API_KEY;if(!key)return[];const out=[];for(const term of TERMS){try{const u=new URL("https://app.ticketmaster.com/discovery/v2/events.json");u.searchParams.set("apikey",key);u.searchParams.set("keyword",term);u.searchParams.set("classificationName","music");u.searchParams.set("size","100");u.searchParams.set("sort","date,asc");u.searchParams.set("locale","*");const data=await jsonFetch(u.href);for(const e of data._embedded?.events||[]){const n=fromTM(e,term);if(n)out.push(n)}}catch{}}return out}
export async function collectBuiltInEvents(){const[stung,ticketmaster]=await Promise.all([collectStung(),collectTM()]);return{events:[...stung,...ticketmaster],stats:{stung:stung.length,ticketmaster:ticketmaster.length}}}
