import dns from "node:dns/promises";
import net from "node:net";
import { normalizeJsonLdEvent, cleanText, safeDate, hashId, normalizeFormat, classifyElectronic } from "./normalize.mjs";

function isPrivateIp(ip){if(net.isIPv4(ip)){const p=ip.split(".").map(Number);return p[0]===10||p[0]===127||p[0]===0||(p[0]===169&&p[1]===254)||(p[0]===172&&p[1]>=16&&p[1]<=31)||(p[0]===192&&p[1]===168)||(p[0]===100&&p[1]>=64&&p[1]<=127)}if(net.isIPv6(ip)){const s=ip.toLowerCase();return s==="::1"||s.startsWith("fc")||s.startsWith("fd")||s.startsWith("fe80:")}return true}
async function assertPublicUrl(input){const u=new URL(input);if(!["http:","https:"].includes(u.protocol))throw new Error("URL non HTTP(S)");const h=u.hostname.toLowerCase();if(h==="localhost"||h.endsWith(".local")||h.endsWith(".internal"))throw new Error("Hôte local refusé");if(net.isIP(h)){if(isPrivateIp(h))throw new Error("Adresse IP privée refusée")}else{const r=await dns.lookup(h,{all:true});if(!r.length||r.some(x=>isPrivateIp(x.address)))throw new Error("Résolution privée refusée")}return u}
async function safeFetch(url,timeoutMs=7000,redirects=0){const u=await assertPublicUrl(url);const c=new AbortController();const timer=setTimeout(()=>c.abort(),timeoutMs);try{const response=await fetch(u,{signal:c.signal,redirect:"manual",headers:{"user-agent":"EventTrack/0.2 (+personal electronic-event aggregator; respectful crawler)",accept:"text/html,application/ld+json,application/xml,text/xml,text/calendar,*/*;q=0.5"}});if([301,302,303,307,308].includes(response.status)){if(redirects>=3)throw new Error("Trop de redirections");const location=response.headers.get("location");if(!location)throw new Error("Redirection sans destination");return safeFetch(new URL(location,u).href,timeoutMs,redirects+1)}if(!response.ok)throw new Error(`HTTP ${response.status}`);return response}finally{clearTimeout(timer)}}
function flattenJsonLd(node,out=[]){if(!node)return out;if(Array.isArray(node)){node.forEach(v=>flattenJsonLd(v,out));return out}if(typeof node!=="object")return out;const type=node["@type"],types=Array.isArray(type)?type:[type];if(types.some(t=>String(t||"").toLowerCase().endsWith("event")))out.push(node);if(node["@graph"])flattenJsonLd(node["@graph"],out);for(const value of Object.values(node)){if(value&&typeof value==="object"&&value!==node["@graph"])flattenJsonLd(value,out)}return out}
function extractJsonLd(html){const events=[];const re=/<script\b[^>]*type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi;let m;while((m=re.exec(html))){let raw=m[1].trim().replace(/^\s*<!--|-->\s*$/g,"");if(!raw)continue;try{flattenJsonLd(JSON.parse(raw),events)}catch{}}return events}
function unfoldIcs(text){return text.replace(/\r?\n[ \t]/g,"")}function icsValue(block,key){return block.match(new RegExp(`^${key}(?:;[^:]*)?:(.*)$`,"mi"))?.[1]?.trim()||""}function parseIcsDate(v){if(!v)return null;if(/^\d{8}T\d{6}Z$/.test(v))return safeDate(`${v.slice(0,4)}-${v.slice(4,6)}-${v.slice(6,8)}T${v.slice(9,11)}:${v.slice(11,13)}:${v.slice(13,15)}Z`);if(/^\d{8}T\d{6}$/.test(v))return safeDate(`${v.slice(0,4)}-${v.slice(4,6)}-${v.slice(6,8)}T${v.slice(9,11)}:${v.slice(11,13)}:${v.slice(13,15)}`);if(/^\d{8}$/.test(v))return safeDate(`${v.slice(0,4)}-${v.slice(4,6)}-${v.slice(6,8)}T00:00:00`);return safeDate(v)}function unescapeIcs(v){return cleanText(v.replace(/\\n/gi," ").replace(/\\,/g,",").replace(/\\;/g,";").replace(/\\\\/g,"\\"),700)}
function parseIcs(text,source){const blocks=unfoldIcs(text).match(/BEGIN:VEVENT[\s\S]*?END:VEVENT/gi)||[];return blocks.map(block=>{const title=unescapeIcs(icsValue(block,"SUMMARY")),startDate=parseIcsDate(icsValue(block,"DTSTART"));if(!title||!startDate)return null;const description=unescapeIcs(icsValue(block,"DESCRIPTION")),cats=unescapeIcs(icsValue(block,"CATEGORIES")),cls=classifyElectronic(`${title} ${cats} ${description}`,source);if(!cls.relevant)return null;const location=unescapeIcs(icsValue(block,"LOCATION")),url=icsValue(block,"URL")||source.url,format=normalizeFormat(`${title} ${cats}`);return{id:hashId(title.toLowerCase(),startDate.slice(0,10),location.toLowerCase()),title,startDate,endDate:parseIcsDate(icsValue(block,"DTEND")),venue:location,city:"",region:"",country:source.country||"",category:format,format,genres:cls.genres,description,imageUrl:"",eventUrl:url,sourceId:source.id,sourceName:source.name,sourceUrl:source.url,confidence:source.trusted?98:92,manual:false,discoveredAt:new Date().toISOString(),updatedAt:new Date().toISOString()}}).filter(Boolean)}
function xmlTag(block,tag){const re=new RegExp(`<${tag}\\b[^>]*>(?:<!\\[CDATA\\[)?([\\s\\S]*?)(?:\\]\\]>)?<\\/${tag}>`,"i");return cleanText(block.match(re)?.[1]||"",700)}
function parseRss(text,source){const blocks=text.match(/<item\b[\s\S]*?<\/item>/gi)||text.match(/<entry\b[\s\S]*?<\/entry>/gi)||[],now=Date.now();return blocks.map(block=>{const title=xmlTag(block,"title"),dateRaw=xmlTag(block,"startDate")||xmlTag(block,"event:startDate")||xmlTag(block,"pubDate")||xmlTag(block,"updated")||xmlTag(block,"published"),startDate=safeDate(dateRaw);if(!title||!startDate||new Date(startDate).getTime()<now-5184000000)return null;const description=xmlTag(block,"description")||xmlTag(block,"summary")||xmlTag(block,"content"),cls=classifyElectronic(`${title} ${description}`,source);if(!cls.relevant)return null;const href=block.match(/<link\b[^>]*href=["']([^"']+)["'][^>]*\/?\s*>/i)?.[1]||xmlTag(block,"link")||source.url,format=normalizeFormat(`${title} ${description}`);return{id:hashId(title.toLowerCase(),startDate.slice(0,10),source.id),title,startDate,endDate:null,venue:"",city:"",region:"",country:source.country||"",category:format,format,genres:cls.genres,description,imageUrl:"",eventUrl:href,sourceId:source.id,sourceName:source.name,sourceUrl:source.url,confidence:source.trusted?74:64,manual:false,discoveredAt:new Date().toISOString(),updatedAt:new Date().toISOString()}}).filter(Boolean)}
function extractEventLinks(html,base){const out=new Set();const origin=new URL(base);const re=/<a\b[^>]*href=["']([^"'#]+)["'][^>]*>([\s\S]*?)<\/a>/gi;let m;while((m=re.exec(html))&&out.size<24){try{const u=new URL(m[1].replace(/&amp;/g,"&"),origin);if(u.hostname!==origin.hostname||!["http:","https:"].includes(u.protocol))continue;const hint=`${u.pathname} ${cleanText(m[2],100)}`;if(!/(event|events|agenda|party|rave|festival|club|night|parade|open.?air|calendar|programm)/i.test(hint))continue;if(/(login|signup|account|privacy|terms|contact|about|artist|venue|ticket\/checkout)/i.test(u.pathname))continue;u.hash="";out.add(u.href)}catch{}}return [...out]}
async function crawlChildPages(html,source){const links=extractEventLinks(html,source.url);if(!links.length)return[];const found=[];for(let i=0;i<links.length;i+=5){const batch=await Promise.allSettled(links.slice(i,i+5).map(async url=>{const r=await safeFetch(url,5500);const t=await r.text();if(t.length>3500000)return[];const childSource={...source,url};return extractJsonLd(t).map(raw=>normalizeJsonLdEvent(raw,childSource)).filter(Boolean)}));for(const r of batch)if(r.status==="fulfilled")found.push(...r.value)}return found}
export async function scrapeSource(source){const response=await safeFetch(source.url);const contentType=(response.headers.get("content-type")||"").toLowerCase();const text=await response.text();if(text.length>6000000)throw new Error("Source trop volumineuse");const kind=source.kind||"auto";let events=[],parser="jsonld";if(kind==="ics"||contentType.includes("text/calendar")||/BEGIN:VCALENDAR/i.test(text.slice(0,1000))){events=parseIcs(text,source);parser="ics"}else if(kind==="rss"||contentType.includes("rss")||contentType.includes("atom")||(/^\s*<\?xml/i.test(text)&&/<(rss|feed)\b/i.test(text.slice(0,3000)))){events=parseRss(text,source);parser="rss"}else{events=extractJsonLd(text).map(raw=>normalizeJsonLdEvent(raw,source)).filter(Boolean);parser="jsonld";if(kind==="auto"){const child=await crawlChildPages(text,source);if(child.length){events.push(...child);parser="jsonld+crawl"}}}return{events,parser}}
